### Create Order 101 via REST
POST http://localhost:8000/order
Content-Type: application/json

{
  "id": "101",
  "price": 100,
  "tax": 10
}

###

### Create Order 102 via REST
POST http://localhost:8000/order
Content-Type: application/json

{
  "id": "102",
  "price": 200,
  "tax": 20
}

###

### List Orders via REST
GET http://localhost:8000/order

###

### Create Order 201 via GraphQL
POST http://localhost:8080/query
Content-Type: application/json

{
  "query": "mutation { createOrder(input: {id:\"201\", Price:300, Tax:30}) { id Price Tax FinalPrice } }"
}

###

### List Orders via GraphQL
POST http://localhost:8080/query
Content-Type: application/json

{
  "query": "query { listOrders { id Price Tax FinalPrice } }"
}